#!/bin/sh

set -e

DEFAULT_PGROOT=/var/lib/postgres

[ -z $PGROOT ] && PGROOT=$DEFAULT_PGROOT

. /etc/conf.d/postgresql

# 2nd clause is necessary to prevent symlinking the directory to itself when it
# doesn't exist yet
if [ ! $DEFAULT_PGROOT -ef "$PGROOT" ] && [ $DEFAULT_PGROOT != "$PGROOT" ]; then
    echo "Creating symlink $DEFAULT_PGROOT -> $PGROOT"

    # Remove $DEFAULT_PGROOT if empty dir, but not if symlink
    if [ ! -L $DEFAULT_PGROOT ] && [ -d $DEFAULT_PGROOT ]; then
        rmdir $DEFAULT_PGROOT
    fi

    ln -sf "$PGROOT" $DEFAULT_PGROOT
fi

PGDATA="$PGROOT/data"

if [ ! -d "$PGDATA" ]; then
    echo "Initializing database in $PGDATA"

    mkdir -p "$PGDATA"
    chown -R postgres:postgres "$PGDATA"

    su - postgres -m -c "/usr/bin/initdb $INITOPTS -D '$PGDATA'" >/dev/null

    if [ -f /etc/postgresql/postgresql.conf ]; then
        ln -sf /etc/postgresql/postgresql.conf "$PGDATA/postgresql.conf"
    fi
fi
