#!/bin/bash

set -e

start="$(date '+%s')"

. /etc/tarsnap/backup.conf

NAME="$(hostname)_$(date -u +%s)"
TMP="/tmp/${NAME}"
OWD="$(pwd)"

mkdir "$TMP"
cd "$TMP"
trap "cd \"$OWD\"; rm -rf \"$TMP\"" EXIT INT TERM


for cmd in "${CMDS[@]}"; do
  sh -c "$cmd"
done

OUT=$(find $TMP -type f)

tarsnap -c -f "$NAME" $OUT "${PATHS[@]}" > /dev/null 2>&1

end="$(date '+%s')"
msg="$(expr $end - $start)s"

test -n "$PING" && curl -d "m=$msg" "$PING" &> /dev/null
