#!/bin/bash

set -e

PREFIX="$(hostname)_"
NAMES="$(tarsnap --list-archives | sort -nr)"
NUM_ARCHIVES=$(echo "$NAMES" | wc -l)
SIZES=$(tarsnap --print-stats --humanize-numbers | grep -oE '[0-9.]+ [a-zA-Z]{2}')

FIRST_STAMP=$(echo "$NAMES" | tail -n 1)
LAST_STAMP=$(echo "$NAMES" | head -n 1)

print_stat() {
  printf "%-30s%20s\n" "$1:" "$2"
}

print_stamp() {
  stamp=${1#$PREFIX}
  echo $(date -d @$stamp +'%F %R')
}

print_stat "Number of archives" "$NUM_ARCHIVES"
print_stat "Total raw" "$(echo "$SIZES" | sed -n 1p)"
print_stat "Total compressed" "$(echo "$SIZES" | sed -n 2p)"
print_stat "Deduped raw" "$(echo "$SIZES" | sed -n 3p)"
print_stat "Deduped compressed" "$(echo "$SIZES" | sed -n 4p)"
print_stat "From" "$(print_stamp $FIRST_STAMP)"
print_stat "To" "$(print_stamp $LAST_STAMP)"
printf "%50s\n" | tr ' ' '-'


num_len=${#NUM_ARCHIVES}
i=$NUM_ARCHIVES
for name in ${NAMES}; do
  printf "%${num_len}s.%$((49-$num_len))s\n" "$((i--))" "$(print_stamp $name)"
done
